language: python

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - python laba4.py < text.txt
  - sbt clean coverage test
 
after_success: 
  - coveralls
