language: python

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - python laba4.py < text.txt\
  - coverage run --source=my_package setup.py test
 
after_success: 
  - coveralls
