language: python

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
# command to run tests
script:
  - python laba4.py < text.txt
  - coverage run --source=tests/ setup.py test
  - py.test tests/laba4.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success: 
  - coveralls

