language: python

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python laba4.py < text.txt
  - py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
  
after_success: 
  - coveralls
